### ISSUE TITLE
Does runwayml SD inpainting only work on square sized images?

### ISSUE THREAD

**Issue by adamhowell** [runwayml/stable-diffusion#13]
I have inpainting working on square images (512x512).

But if I try to do inpainting on landscape and portrait sized images (512x320 and 384x512 respectively (ie divided by 8)) I get:

`RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 64 but got size 40 for tensor number 2 in the list.`

`RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 64 but got size 48 for tensor number 2 in the list.`

Does runwayml's diffusers inpainting only work on square images? (and if so, should maybe mention that in the documentation somewhere unless I missed it) Thanks!

**Comment by adamhowell** [comment]
Never mind I now see the height and width parameters!

**Comment by soumitri2001** [comment]
@adamhowell could you pls let me know where are the h and w params and how to enable the pipeline for non-square images?
