### ISSUE TITLE
Result variation from stable diffusion model, thanks

### ISSUE THREAD

**Issue by junyongyou** [runwayml/stable-diffusion#20]
Dear all, I am quite new to stable diffusion, and just tried the code. However, when I was using the same script to create an image, I got different images when running the script again. Is it a parameter that can be set to create identical image with the same script and same prompt? Thanks a lot.

**Comment by himmetozcan** [comment]
use same seed number

**Comment by junyongyou** [comment]
Aha, yes, I forgot that. Thanks and I will try.
